# Generated by Django 6.0.1 on 2026-02-03 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процентная скидка'), ('fixed', 'Фиксированная сумма')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер скидки')),
                ('applicable_products', models.TextField(help_text='ID продуктов через запятую', verbose_name='Применимые продукты')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Промоакция',
                'verbose_name_plural': 'Промоакции',
                'db_table': 'promotions',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflicting_products', models.TextField(help_text='ID продуктов через запятую', verbose_name='Конфликтующие продукты')),
                ('overlap_start', models.DateTimeField(verbose_name='Начало пересечения')),
                ('overlap_end', models.DateTimeField(verbose_name='Конец пересечения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Разрешён')),
                ('resolution_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод разрешения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обнаружен')),
                ('promotion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='promotions.promotion')),
                ('promotion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Конфликт промоакций',
                'verbose_name_plural': 'Конфликты промоакций',
                'db_table': 'promotion_conflicts',
                'unique_together': {('promotion1', 'promotion2')},
            },
        ),
    ]
