# Generated by Django 6.0.1 on 2026-02-03 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID клиента')),
                ('loyalty_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы лояльности')),
                ('membership_status', models.CharField(choices=[('Basic', 'Basic'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Basic', max_length=20, verbose_name='Статус членства')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_points_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Последний расчёт баллов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
                'db_table': 'loyalty_program',
                'ordering': ['-loyalty_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Начисление'), ('redeem', 'Списание'), ('adjustment', 'Корректировка'), ('bonus', 'Бонус')], max_length=20, verbose_name='Тип транзакции')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID заказа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Транзакция лояльности',
                'verbose_name_plural': 'Транзакции лояльности',
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('fixed_discount', 'Скидка 5€'), ('percentage_discount', 'Скидка 10%'), ('membership_upgrade', 'Повышение уровня')], max_length=30, verbose_name='Тип награды')),
                ('points_spent', models.IntegerField(default=1000, verbose_name='Потрачено баллов')),
                ('promotion_id', models.IntegerField(blank=True, null=True, verbose_name='ID промоакции')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обмена')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Обмен награды',
                'verbose_name_plural': 'Обмены наград',
                'db_table': 'reward_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
